Repository gacela-project/gacela-project.com, pull requests merged in 2022-02, with the labels that each got.

#15 Remove from Config the documentation related to .env
  config.toml
  content/about-gacela/config/_index.md
Labels: documentation

#16 Update design
  config.prod.toml
  config.toml
  content/about-gacela/_index.md
  content/about-gacela/config/_index.md
  content/about-gacela/dependency-provider/_index.md
  content/about-gacela/facade/_index.md
  content/about-gacela/factory/_index.md
  content/docs/_index.md
  content/docs/code-generator/_index.md
  content/docs/config/_index.md
  content/docs/dependency-provider/_index.md
  content/docs/facade/_index.md
  content/docs/factory/_index.md
  content/docs/modules/_index.md
  content/docs/why-decoupling/_index.md
  sass/_base.scss
  sass/_custom.scss
  sass/_menu.scss
  sass/site.scss
  templates/base.html
  templates/home.html
  templates/section.html
Labels: documentation, enhancement

#17 Replace "GitHub" text from menu to icon
  config.prod.toml
  config.toml
  sass/_menu.scss
  static/dark-mode.js
  templates/base.html
Labels: enhancement

#19 Improve content/docs
  content/docs/_index.md
  content/docs/config.md
  content/docs/dependency-provider.md
  content/docs/facade.md
  content/docs/factory.md
  content/docs/gacela-bootstrap.md
  content/docs/gacela-php.md
  sass/_base.scss
  sass/_header.scss
  templates/navigation/top-navigation.html
Labels: documentation
